title: Leijun Jiang's blogs
author: Leijun Jiang
email: leijunjiang@gmail.com

github_username:   leijunjiang
linkedin_username: leijun-jiang-82882678


# Build settings
theme: minima
plugins:
  - jekyll-feed

# The github repo that is to be used for looking up comments
comments_repo: leijunjiang/leijunjiang.github.io
